momentohq/client-sdk-swift

- Sources/momento/TopicClient.swift
- Sources/momento/config/logging/DefaultMomentoLogger.swift
- Sources/momento/config/logging/LogProvider.swift
- Sources/momento/internal/PubsubClient.swift
- Sources/momento/messages/responses/topics/TopicSubscribe.swift
Tried Pete's suggestion of creating a LogProvider class with static methods that can be accessed internally by momento code, such as the `TopicSubscribeSuccess` class.
Think I found a better way to pass the logger along by lazily initializing the `TopicSubscribeSuccess.subscription` variable.
Ended up creating a new logger that will specifically log messages from the `TopicSubscribeSuccess` class.
Not sure if this is the best way to go about logging the messages, but I couldn't bring the `processResult` function into the `TopicSubscribeSuccess` due to the init function, which uses the processResult function before the class is fully initialized (or at least that's my understanding of it).
```
init(subscription: GRPCAsyncResponseStream<CacheClient_Pubsub__SubscriptionItem>) { …
```
> chore: use logger that prints to stderr

- Sources/momento/TopicClient.swift
- Sources/momento/internal/PubsubClient.swift
During my first attempt at consuming the momento package through a url in an example app, I discovered that it would not let me build when `iOS 13` was missing from the `available` tags on the TopicClient and PubsubClient.
> fix: available tags should include iOS 13

- .github/workflows/test.yml
- .gitignore
- Examples/topics/Package.resolved
- Examples/topics/Package.swift
- README.md
Addresses #53 
Need to ensure that target dependencies are able to find the Momento SDK by specifying `.product(name: "momento", package: "client-sdk-swift")`
> chore: topics example should consume package from url and github actions should build example in ci

- Sources/momento/auth/CredentialProvider.swift
- Tests/momentoTests/authTests.swift
This commit adds detection and error handling for a relatively common error condition encountered when trying to parse JWTs and a test to verify the condition is handled properly.
> fix: add missing error handling for JWT token and tests

- Sources/momento/CacheClient.swift
- Sources/momento/TopicClient.swift
- Sources/momento/internal/utils/Validators.swift
- Tests/momentoTests/cacheTests.swift
Our validation here is too strict, as it is perfectly valid for users to supply empty and blank strings for cache values and messages published to topics. Some other SDKs have logic to prevent `null`/`nil`/`None` values, but in this SDK the compiler will handle that for us.
> chore: remove validation disallowing empty and blank cache values

- .github/workflows/test.yml
- Examples/topics/Package.swift
Topics example should use swift-tools-version 5.7 and CI should actually `cd` into the topics directory to build the example
> fix: actually build the topics example in ci

- Sources/Momento/config/CacheConfigurations.swift
- Sources/Momento/config/TopicConfigurations.swift
- Tests/MomentoTests/configTests.swift
- Tests/MomentoTests/testUtils.swift
Addresses #81 except for the docstrings; I'll come back to that with the docstrings ticket
> chore: rename prebuilt config classes and targets for clarity

- Sources/Momento/errors/Errors.swift
- Sources/Momento/messages/responses/ResponseBase.swift
- Sources/Momento/messages/responses/cache/control/ListCaches.swift
- Sources/Momento/messages/responses/cache/data/list/ListConcatenateBack.swift
- Sources/Momento/messages/responses/cache/data/list/ListConcatenateFront.swift
- Sources/Momento/messages/responses/cache/data/list/ListFetch.swift
- Sources/Momento/messages/responses/cache/data/list/ListLength.swift
- Sources/Momento/messages/responses/cache/data/list/ListPopBack.swift
- Sources/Momento/messages/responses/cache/data/list/ListPopFront.swift
- Sources/Momento/messages/responses/cache/data/list/ListPushBack.swift
- Sources/Momento/messages/responses/cache/data/list/ListPushFront.swift
- Sources/Momento/messages/responses/cache/data/scalar/Get.swift
- Sources/Momento/messages/responses/topics/TopicSubscriptionItem.swift
Addresses #84 
By default, printing response classes that don't have associated values will print their class names:
```
success(Momento.CreateCacheSuccess)
alreadyExists(Momento.CreateCacheAlreadyExists)
miss(Momento.GetMiss)
```
Adding these custom strings allow for more informational prints about errors and classes with associated values:
```
success([ListCachesSuccess] Length of caches list: 4)
hit([GetHit] Value: xyz)
success([ListConcatenateFrontSuccess] List length post-concatenation: 2)
hit([ListFetchHit] List length: 2)
error([INVALID_ARGUMENT_ERROR] Invalid argument passed to Momento client: Invalid cache name)
```
> chore: add custom strings to print response types and values if applicable

- Examples/doc-example-apis/Sources/main.swift
The snippets were incorrectly named. They should show up in the API reference page for `publish` and `subscribe` after this goes in
> chore: rename topics doc sample snippets

- Sources/Momento/CacheClient.swift
- Sources/Momento/internal/ControlClient.swift
- Sources/Momento/internal/DataClient.swift
addresses #111 
Inspected the very large codeql log output and I think it was mostly just complaining that the cache client protocols were missing the `@available` tags
> fix: add available attribute to cache client protocols

- README.md
- Sources/Momento/TopicClient.swift
- Sources/Momento/internal/PubsubClient.swift
- Sources/Momento/internal/TopicsGrpcManager.swift
- Sources/Momento/messages/responses/ResponseBase.swift
- Sources/Momento/messages/responses/topics/TopicSubscribe.swift
Addresses https://github.com/momentohq/client-sdk-swift/issues/106 and part of https://github.com/momentohq/dev-eco-issue-tracker/issues/604 (will need to follow up to update the topics example after this is released).
Creates a Topics GRPC manager class to allow multiple GRPC connections in the pubsub client if needed in the future.
Adds logic for resubscribing on errors that are not cancellation errors.
Adds a way to unsubscribe from a topic (essentially stops the AsyncStream providing the messages).
Manually tested using topics example that it will resubscribe when wifi is turned off for a few minutes and that it will not resubscribe when the user calls unsubscribe to cancel the subscription. 
If you want to test it yourself, the `Package.swift` was modified like so:
```
// …
```
> feat: topics subscription resiliency

- Sources/Momento/CacheClient.swift
- Sources/Momento/TopicClient.swift
- Sources/Momento/internal/PubsubClient.swift
- Sources/Momento/internal/TopicsGrpcManager.swift
- Sources/Momento/messages/responses/topics/TopicSubscribe.swift
Followup addressing https://github.com/momentohq/client-sdk-swift/issues/106
Unsubscribe was not working correctly (not freeing up the subscription stream). Went back to look at the proto-generated stubs and found `makeSubscribeCall()` as an alternate way to subscribe to a topic, and the response for this method comes with a `cancel()` method and the `AsyncResponseStream` we had been using before. Verified with local testing that resources are actually freed up once a subscription is canceled.
Also implemented a way to check the first message of a subscription, and if it's not a heartbeat, it should return an error. This way, it's possible to send a TopicSubscribeError when all streams are maxed out rather than returning a subscription that will error the first time the user tries to use …
> fix: availability tag and topics subscriptions fixes

- Sources/Momento/CacheClient.swift
- Sources/Momento/TopicClient.swift
- Sources/Momento/auth/CredentialProvider.swift
- Sources/Momento/config/CacheConfiguration.swift
- Sources/Momento/config/TopicConfiguration.swift
- Sources/Momento/messages/responses/cache/control/CreateCache.swift
- Sources/Momento/messages/responses/cache/control/DeleteCache.swift
- Sources/Momento/messages/responses/cache/control/ListCaches.swift
- Sources/Momento/messages/responses/cache/data/list/ListConcatenateBack.swift
- Sources/Momento/messages/responses/cache/data/list/ListConcatenateFront.swift
- Sources/Momento/messages/responses/cache/data/list/ListFetch.swift
- Sources/Momento/messages/responses/cache/data/list/ListLength.swift
- Sources/Momento/messages/responses/cache/data/list/ListPopBack.swift
- Sources/Momento/messages/responses/cache/data/list/ListPopFront.swift
- Sources/Momento/messages/responses/cache/data/list/ListPushBack.swift
- Sources/Momento/messages/responses/cache/data/list/ListPushFront.swift
- Sources/Momento/messages/responses/cache/data/list/ListRemoveValue.swift
- Sources/Momento/messages/responses/cache/data/list/ListRetain.swift
- Sources/Momento/messages/responses/cache/data/scalar/Delete.swift
- Sources/Momento/messages/responses/cache/data/scalar/Get.swift
- Sources/Momento/messages/responses/cache/data/scalar/Set.swift
- Sources/Momento/messages/responses/topics/TopicPublish.swift
- Sources/Momento/messages/responses/topics/TopicSubscribe.swift
- Sources/Momento/messages/responses/topics/TopicSubscriptionItem.swift
Addressing bug bash feedback, #115 and #116, and specifies language as `swift` for docstring code snippets
> chore: small error message and docstring fixes

- .github/workflows/test.yml
- CONTRIBUTING.md
- Examples/README.md
- Examples/cache/Package.resolved
- Examples/cache/Package.swift
- Examples/cache/README.md
- Examples/cache/Sources/main.swift
- Examples/demo-chat-app/README.md
- Examples/demo-chat-app/demo-chat-app.xcodeproj/project.pbxproj
- Examples/demo-chat-app/demo-chat-app.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Examples/demo-chat-app/demo-chat-app.xcodeproj/xcshareddata/xcschemes/demo-chat-app.xcscheme
- Examples/demo-chat-app/demo-chat-app/MessageStore.swift
- Examples/demo-chat-app/demo-chat-app/MomentoDemoChatApp.swift
- Examples/doc-example-apis/Package.resolved
- Examples/doc-example-apis/Package.swift
- Examples/doc-example-apis/Sources/main.swift
- Examples/quickstart/Package.resolved
- Examples/quickstart/Package.swift
- Examples/quickstart/README.md
- Examples/topics/Package.resolved
- Examples/topics/Package.swift
- Examples/topics/README.md
- Examples/topics/Sources/main.swift
- README.template.md
Addresses the last two tasks of https://github.com/momentohq/dev-eco-issue-tracker/issues/604 
- Updates all examples to use the latest release (0.4.0)
- Subscribe examples now use switch expressions to assign subscriptions directly (if using >= Swift 5.9)
- Showed how to use `unsubscribe` in the topics example and in the docs example
- For the examples that are run in CI, `exit(1)` whenever an error occurs instead of simply printing errors (#109)
- Runs the cache example in CI instead of just building it
- iOS sample app uses `MOMENTO_API_KEY` env var instead of hardcoded string
- Updated readme template to use v0.4.0
- Updated links in readmes to point to specifically the api-keys page or cache page as appropriate
> chore: update examples to use latest release and other small updates

- README.template.md
Usage section of the generated readme was missing the code block formatting
> chore: readme template was missing code block markdown for usage section

- Sources/Momento/CacheClient.swift
- Sources/Momento/internal/ControlClient.swift
- Sources/Momento/internal/DataClient.swift
Adds a `close` method to the CacheClient. I think this will be needed to prevent an ever-growing number of grpc connections in the ios moderated chat demo whenever the disposable token and the cache and topic clients need to be refreshed.
Also fixed the docstring mentioned in https://github.com/momentohq/client-sdk-swift/issues/129
> feat: add close method to CacheClient

- Sources/Momento/CacheClient.swift
- Sources/Momento/TopicClient.swift
- Sources/Momento/errors/Errors.swift
- Sources/Momento/internal/ControlClient.swift
- Sources/Momento/internal/DataClient.swift
- Sources/Momento/internal/PubsubClient.swift
- Sources/Momento/messages/responses/topics/TopicSubscribe.swift
`innerException` already exists on the `SdkError` object, just forgot to pass it in in many places where we create UnknownError objects. Should be easier to tell the distinction between our error message and the received error message as well.
> fix: pass errors as innerException and don't auto-resubscribe when connection becomes unavailable

- Sources/Momento/internal/ControlClient.swift
- Sources/Momento/internal/DataClient.swift
- Sources/Momento/internal/PubsubClient.swift
- Sources/Momento/internal/utils/PackageVersion.swift
- Add one time headers: `agent` and `runtime-version`
https://github.com/momentohq/dev-eco-issue-tracker/issues/897
> feat: add onetime headers

- Sources/Momento/errors/Errors.swift
Was running into `'get()' is only available in iOS 13 or newer` error while checking the moderated chat demo with the latest Swift package version.
Realized the `if #available` check was missing iOS 13, and also it's inconsistent with our usage of `@available` everywhere else in the SDK. Changed to `@available(macOS 10.15, iOS 13, *)` encompassing the entire function instead.
> fix: use @available tag instead of if statement in processError

- Examples/demo-chat-app/demo-chat-app.xcodeproj/project.pbxproj
- Examples/demo-chat-app/demo-chat-app.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Examples/demo-chat-app/demo-chat-app.xcodeproj/xcshareddata/xcschemes/demo-chat-app.xcscheme
Work towards https://github.com/momentohq/dev-eco-issue-tracker/issues/1067
We recently added support for topics sequence page in the SDKs. This PR upgrades the Momento dependency in this repo's demo chat app example.
> chore: upgrade momento dep in demo chat app example
